version: '2'
services:
  db:
    image: postgres
    ports:
      - "3307:3307"
    volumes:
      - postgres:/var/lib/pgsql
    env_file: ./.environments/postgres.env
  api:
    build: 
      context: .
    command: bundle exec rails s
    volumes:
      - .:/myapp
      - bundle_install:/usr/local/bundle
    env_file:
      - ./.environments/postgres.env
      - ./.environments/rails.env
    ports:
      - "3030:3030"
      - "8081:8081"
    depends_on:
      - db
volumes:
  postgres:
    driver: local
  bundle_install:
    driver: local
